import{a as w,S as I,i as d}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const v="47534092-804b13b479cbd901190151ed2",B="https://pixabay.com/api/";async function g(t,o=1,i=15){const n={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:i},{data:e}=await w.get(B,{params:n});if(!e.hits.length)throw new Error("No images found");return e}const O=new I(".gallery a");function h(t){const o=document.getElementById("gallery"),i=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:l,views:b,comments:L,downloads:E})=>`
        <li class="gallery-item">
          <a href="${e}">
            <img src="${n}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${l}</p>
            <p><b>Views:</b> ${b}</p>
            <p><b>Comments:</b> ${L}</p>
            <p><b>Downloads:</b> ${E}</p>
          </div>
        </li>`).join("");o.innerHTML=i,O.refresh()}function P(){const t=document.getElementById("gallery");t.innerHTML=""}const $=document.getElementById("search-form"),C=document.getElementById("search-input"),p=document.getElementById("gallery"),x=document.getElementById("loader"),s=document.createElement("button");let c="",a=1;const u=15;let f=0;s.textContent="Load more";s.classList.add("hidden");p.parentNode.appendChild(s);$.addEventListener("submit",async t=>{if(t.preventDefault(),c=C.value.trim(),!c){d.error({title:"Error",message:"Please enter a search term!"});return}a=1,P(),m(!0),s.classList.add("hidden");try{const o=await g(c,a,u);f=o.totalHits,h(o.hits),a*u<f?s.classList.remove("hidden"):y()}catch(o){d.error({title:"Error",message:o.message})}finally{m(!1)}});s.addEventListener("click",async()=>{a+=1,m(!0);try{const t=await g(c,a,u);h(t.hits),a*u>=f?(s.classList.add("hidden"),y()):H()}catch(t){d.error({title:"Error",message:t.message})}finally{m(!1)}});function m(t){x.classList.toggle("hidden",!t)}function y(){d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}function H(){const{height:t}=p.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
